# Generated by Django 5.2 on 2025-04-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamentocatalogo',
            old_name='frecuencias_disponibles',
            new_name='frecuencia',
        ),
        migrations.RenameField(
            model_name='medicamentocatalogo',
            old_name='vias_disponibles',
            new_name='via',
        ),
    ]
