# Generated by Django 5.2 on 2025-04-18 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudexamen',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_examenes', to='pacientes.paciente'),
        ),
        migrations.CreateModel(
            name='Epicrisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('diagnostico_egreso', models.TextField()),
                ('indicaciones_alta', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrador.perfilusuario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epicrisis', to='pacientes.paciente')),
            ],
        ),
    ]
