# Generated by Django 5.2 on 2025-04-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
