# Generated by Django 5.2 on 2025-04-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_delete_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cama',
            name='numero',
            field=models.CharField(),
        ),
    ]
