# Generated by Django 5.2 on 2025-07-10 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pacientes",
            "0002_rename_frecuencias_disponibles_medicamentocatalogo_frecuencia_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Antecedente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("morbido", "Mórbido"),
                            ("quirurgico", "Quirúrgico"),
                            ("alergia", "Alergia"),
                            ("familiar", "Familiar"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antecedentes",
                        to="pacientes.paciente",
                    ),
                ),
            ],
        ),
    ]
