# Generated by Django 5.2.4 on 2025-07-12 15:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0003_antecedente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("reposo", models.CharField(blank=True, max_length=100)),
                ("regimen", models.CharField(blank=True, max_length=100)),
                ("medicamentos", models.TextField(blank=True)),
                ("infusiones", models.TextField(blank=True)),
                ("dispositivos", models.TextField(blank=True)),
                ("otras", models.TextField(blank=True)),
                (
                    "episodio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicaciones",
                        to="pacientes.episodio",
                    ),
                ),
            ],
        ),
    ]
