# Generated by Django 5.2 on 2025-04-20 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_rename_fecha_epicrisis_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='epicrisis',
            name='indicaciones_alta',
        ),
        migrations.AddField(
            model_name='epicrisis',
            name='indicaciones_controles',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='epicrisis',
            name='indicaciones_generales',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MedicamentoEpicrisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
                ('via', models.CharField(max_length=100)),
                ('epicrisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_indicados', to='pacientes.epicrisis')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.medicamento')),
            ],
        ),
    ]
