# Generated by Django 5.2 on 2025-04-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_medicamento_remove_epicrisis_indicaciones_alta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='hospitalizado',
            field=models.BooleanField(default=True),
        ),
    ]
