# Generated by Django 5.2.4 on 2025-07-17 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0004_indicacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaTexto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("evolucion", "Evolución"),
                            ("indicacion", "Indicación"),
                            ("indicacion_general", "Indicación General Epicrisis"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=100)),
                ("contenido", models.TextField()),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantillas_texto",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
