# Generated by Django 5.2 on 2025-04-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_paciente_hospitalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_egreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
