# Generated by Django 5.2.4 on 2025-07-21 02:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_initial'),
        ('pacientes', '0005_plantillatexto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudexamen',
            name='categoria',
            field=models.CharField(choices=[('imagen', 'Imagenología'), ('laboratorio', 'Laboratorio')], default='laboratorio', max_length=20),
        ),
        migrations.CreateModel(
            name='EvaluacionEnfermeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('contenido', models.TextField()),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_enfermeria', to='pacientes.episodio')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_enfermeria', to='administrador.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='SignoVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('presion_arterial', models.CharField(blank=True, max_length=20)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, null=True)),
                ('saturacion', models.IntegerField(blank=True, null=True)),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='pacientes.episodio')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signos_vitales_registrados', to='administrador.perfilusuario')),
            ],
        ),
    ]
