# Generated by Django 5.2 on 2025-04-25 00:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_alter_paciente_fecha_egreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamentoepicrisis',
            name='medicamento',
        ),
        migrations.RemoveField(
            model_name='medicamentoepicrisis',
            name='epicrisis',
        ),
        migrations.RemoveField(
            model_name='epicrisis',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='evolucion',
            name='paciente',
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_egreso', models.DateTimeField(blank=True, null=True)),
                ('motivo_ingreso', models.TextField(blank=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('cama', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.cama')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='pacientes.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='epicrisis',
            name='episodio',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='epicrisis', to='pacientes.episodio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evolucion',
            name='episodio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='pacientes.episodio'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Medicamento',
        ),
        migrations.DeleteModel(
            name='MedicamentoEpicrisis',
        ),
    ]
