# Generated by Django 5.2.4 on 2025-07-21 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0002_initial"),
        ("pacientes", "0007_rename_tipo_examen_examenes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pabellon", "Solicitud de Pabellón"),
                            ("transfusion", "Solicitud de Transfusión"),
                            ("traslado", "Solicitud de Traslado"),
                            ("certificado", "Certificado Médico"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detalle", models.TextField(blank=True)),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes_generadas",
                        to="administrador.perfilusuario",
                    ),
                ),
            ],
        ),
    ]
