# Generated by Django 5.2.4 on 2025-07-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0008_solicitud"),
    ]

    operations = [
        migrations.AddField(
            model_name="epicrisis",
            name="condicion_mejorado",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="epicrisis",
            name="detalle_examenes_pendientes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="epicrisis",
            name="detalle_examenes_realizados",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="epicrisis",
            name="examenes_pendientes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="epicrisis",
            name="examenes_realizados",
            field=models.BooleanField(default=False),
        ),
    ]
